[package]
name = "stm32-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["rayon"]
rayon = ["dep:rayon"]

[dependencies]
anyhow = "1.0.66"
glob = "0.3.0"
num = "0.4.0"
quick-xml = { version = "0.26.0", features = ["serialize"] }
regex = "1.6.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_yaml = "0.9.14"
chiptool = { git = "https://github.com/embassy-rs/chiptool", rev = "1d9e0a39a6acc291e50cabc4ed617a87f06d5e89" }
serde_json = "1.0.87"
rayon = { version = "1.5.3", optional = true }
stm32-data-serde = { version = "0.1.0", path = "stm32-data-serde" }
ref_thread_local = "0.1.1"

# Optimize for dev experience: shortest "build+run" time after making a small change.
[profile.release]
debug = true
incremental = true
panic = 'abort'
opt-level = 2